"""code table

Revision ID: 00008565fd3b
Revises: 6a8cb02c279d
Create Date: 2021-05-03 23:23:17.394775

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '00008565fd3b'
down_revision = '6a8cb02c279d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('code', sa.String(length=5), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'surname')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('surname', sa.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_table('code')
    # ### end Alembic commands ###
