"""code if_used

Revision ID: 17fdbdd232c5
Revises: 00008565fd3b
Create Date: 2021-05-03 23:39:04.343039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17fdbdd232c5'
down_revision = '00008565fd3b'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code', sa.Column('if_used', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code', 'if_used')
    # ### end Alembic commands ###
