"""candidate number

Revision ID: 2c7d7b3b6efa
Revises: 17fdbdd232c5
Create Date: 2021-05-04 20:50:14.935236

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2c7d7b3b6efa'
down_revision = '17fdbdd232c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('number', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'number')
    # ### end Alembic commands ###
