"""empty message

Revision ID: 3530d1b7b42e
Revises: fb060e6ed9f9
Create Date: 2021-04-27 23:08:31.871153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3530d1b7b42e'
down_revision = 'fb060e6ed9f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=True))
    op.drop_index('ix_user_name', table_name='user')
    op.drop_index('ix_user_surname', table_name='user')
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_surname', 'user', ['surname'], unique=False)
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    op.drop_column('user', 'username')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
