"""candidate_table

Revision ID: 6a8cb02c279d
Revises: 3530d1b7b42e
Create Date: 2021-04-28 19:48:25.002873

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6a8cb02c279d'
down_revision = '3530d1b7b42e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('surname', sa.String(length=64), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'surname')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('surname', sa.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_table('candidate')
    # ### end Alembic commands ###
